### ISSUE TITLE
Update README about `/leases` JSON endpoint

### ISSUE THREAD

**Issue by xakraz** [fschlag/dnsmasq-leases-ui#2]
Hello,

By using your app, I noticed the endpoint `/leases` allow the user to retrieve the leases in JSON.
This is great and I think you should advertise it in your readme :)

Tell me if you want me to suggest a PR for that,

**Comment by fschlag** [comment]
Hi,

yes that's worth to mention.

Feel free to suggest a PR. 👍 

Thanks!

**Comment by fschlag** [comment]
Added documentation with fb047ce35096e7349d49dba2ef3a14f1056d9b64
